# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/tommi/Linux_Unreal_Engine_5.1.1
GAMEPROJECTFILE =/home/tommi/Invaders/Invaders.uproject

TARGETS = \
	Invaders-Linux-DebugGame  \
	Invaders-Linux-Shipping  \
	Invaders \
	InvadersEditor-Linux-DebugGame  \
	InvadersEditor-Linux-Shipping  \
	InvadersEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend InvadersEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug InvadersEditor-Linux-Debug


Invaders-Linux-DebugGame:
	 $(PROJECTBUILD) Invaders Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Invaders-Linux-Shipping:
	 $(PROJECTBUILD) Invaders Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Invaders:
	 $(PROJECTBUILD) Invaders Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

InvadersEditor-Linux-DebugGame:
	 $(PROJECTBUILD) InvadersEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

InvadersEditor-Linux-Shipping:
	 $(PROJECTBUILD) InvadersEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

InvadersEditor:
	 $(PROJECTBUILD) InvadersEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
